on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

jobs:
  lintAndTest:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn config set ignore-engines true
          yarn --frozen-lockfile --ignore-scripts

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test

      - name: Building
        if: success()
        run: yarn build

  publish:
    if: github.ref == 'refs/heads/master'
    needs: lintAndTest
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@master
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          yarn config set ignore-engines true
          yarn --frozen-lockfile --ignore-scripts

      - name: Building
        run: yarn build

      - name: Release
        uses: cycjimmy/semantic-release-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
