on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "**.js"
      - "**.ts"
      - "**/package.json"
      - "**/package-lock.json"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

env:
  node: "16"

jobs:
  integrate:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test

      - name: Building
        if: success()
        run: yarn build

      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v1

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"

      # - name: Create Artifact
      #   uses: actions/upload-artifact@v2
      #   if: success()
      #   with:
      #     # Artifact name
      #     name: release
      #     # A file, directory or wildcard pattern that describes what to upload
      #     path: dist/
